config/routes.rb
Rails.application.routes.draw do
  resources :libraries
  devise_for :users
  # get 'home/index'
  # root 'home#index'
  root 'libraries#index'
  resources :books

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    has_many :libraries
end

app/models/library.rb
class Library < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :books
         has_many :libraries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:date_of_birth, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:date_of_birth, :email, :password, :current_password)}
         end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user! , except: [:index , :show]  #before yousignin you cant do any action eccept show and index
  before_action :corerct_user , only: [:edit , :update , :destroy]

  # GET /books or /books.json
  def index
    @books = Book.all
    @library = Library.all
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    # @book = Book.new
    @book = current_user.books.build

    all_lib_name = []
    for lib_name in Library.all do
        all_lib_name = all_lib_name.push(lib_name.library_name)
    end
    @library = all_lib_name
  end

  # GET /books/1/edit
  def edit
    all_lib_name = []
    for lib_name in Library.all do
        all_lib_name = all_lib_name.push(lib_name.library_name)
    end
    @library = all_lib_name
  end

  # POST /books or /books.json
  def create
    # @book = Book.new(book_params)

    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
    @library = Library.all
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end

    @library = Library.all
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def corerct_user
      @book = current_user.books.find_by(id: params[:id])
      redirect_to books_path, notice: "Not autorized edit this book" if @book.nil?
    end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:book_name, :author_name, :library_id, :user_id , :library_name , :language)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[ show edit update destroy ]
  before_action :authenticate_user! , except: [:index , :show]  #before yousignin you cant do any action eccept show and index
  before_action :corerct_user , only: [:edit , :update , :destroy]

  # GET /libraries or /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1 or /libraries/1.json
  def show

    all_book_name = []
    for book_name in Book.all do
       if book_name.library_name == @library.library_name

        all_book_name = all_book_name.push(book_name.book_name)

       end
    end

    @book = all_book_name 

    @book1 = Book.all 



  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries or /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save(validate: false)
        format.html { redirect_to library_url(@library), notice: "Library was successfully created." }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1 or /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to library_url(@library), notice: "Library was successfully updated." }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1 or /libraries/1.json
  def destroy
    @library.destroy

    respond_to do |format|
      format.html { redirect_to libraries_url, notice: "Library was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def corerct_user
    @library = current_user.libraries.find_by(id: params[:id])
    redirect_to libraries_path, notice: "Not autorized edit this library" if @library.nil?
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def library_params
      params.require(:library).permit(:library_name, :opening_time, :closing_time, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Book name:</strong>
    <%= book.book_name %>
  </p>

  <p>
    <strong>Author name:</strong>
    <%= book.author_name %>
  </p>

  <p>
    <strong>Library:</strong>
    <%= book.library_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= book.user_id %>
  </p>

</div>

app/views/books/_form.html.erb
<div class="container">


<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :book_name, style: "display: block" %>
    <%= form.text_field :book_name %>
  </div>

  <div>
    <%= form.text_field :author_name , type: :hidden , value:current_user.email if current_user %>
  </div>

   <div>
    <%= form.label :language, style: "display: block"%>
    <%= form.text_field :language , class: "mb-5" %>
  </div>



  <div>
    <%= form.number_field :user_id, required: true, class: 'form-control', type: :hidden , value:current_user.id if current_user   %>
  </div>


<div>
<%= form.label :library_name, style: "display: block"%>
<%= form.select(:library_name, @library , :class => 'my_style_class', required: true )%>
</div>

  <div>
  <br>
    <%= form.submit %>
  </div>
<% end %>


</div>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="books">

<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Book name</th>
      <th scope="col">Author ID</th>
      <th scope="col">Created Date</th>
      <th scope="col">Updated Date</th>
      <th scope="col">View</th>

    </tr>
  </thead>
  <tbody>

<% i=1 %>

  <% @books.each do |book| %>  
<% # if book.user_id == current_user.id %>

<% user = User.find_by(id: book.library_id) %>
   
      <tr>
      <th scope="row"> <%= i %> </th>
       <td> <%=  book.book_name %></td>
      <td><%= book.user_id %> </td>
      <td> <%= book.created_at %> </td>
      <td> <%= book.updated_at %> </td>
      <td>   <%= link_to "Show this book", book , class: "btn btn-success btn-sm " %> </td>
    </tr>

    <% i=i+1 %>

  <% #end %>

  <% end %>
</div>

<% if user_signed_in? %>
<%= link_to "Add New book", new_book_path , class: "btn btn-success btn-sm mb-5" %>
<% end %>

</tbody>
</table>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="" style="width: 18rem;">
  <div class="card-body">

  <%# user = User.find_by(id: @book.library_name) %>

<div class="card" style="width: 18rem;">
  <div class="card-body">
<h5 class="card-title"> <%= @book.book_name %> </h5>
 <h6 class="card-subtitle mb-2 text-muted mb-5"> <%= @book.author_name %> </h6>
 <h6 class="card-subtitle mb-2 text-muted mb-5"> <%= @book.library_name %> </h6>
    <h6 class="card-subtitle mb-2 text-muted mb-5"> language : <%= @book.language %> </h6>
    
    <h6 class="card-subtitle mb-2 text-muted"> Created date : <%= @book.created_at %> </h6>
    <h6 class="card-subtitle mb-2 text-muted">updated date : <%= @book.updated_at %> </h6> <br>
    <hr>

    <%= link_to "Edit this book", edit_book_path(@book) , class: "card-link" %>

   <%= link_to "Back to books", books_path , class: "card-link"%>

    <%= button_to "Destroy this book", @book, method: :delete , class: "btn btn-danger btn-sm mt-5 "%>


  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>LibraryApp</title>
  </head>
  <body>
       <%= render 'nabar/navbar'%>

      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <div class='container mt-3'>
      <%= yield %>
      </div>
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/libraries/_form.html.erb
<%= form_with(model: library) do |form| %>
  <% if library.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
        <% library.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :library_name, style: "display: block" %>
    <%= form.text_field :library_name %>
  </div>

  <div>
    <%= form.label :opening_time, style: "display: block" %>
    <%= form.time_field :opening_time %>
  </div>

  <div>
    <%= form.label :closing_time, style: "display: block" %>
    <%= form.time_field :closing_time %>
  </div>

  <div>
       <%= form.number_field :user_id, required: true, class: 'form-control', type: :hidden , value:current_user.id if current_user   %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/_library.html.erb
<div id="<%= dom_id library %>">
  <p>
    <strong>Library name:</strong>
    <%= library.library_name %>
  </p>

  <p>
    <strong>Opening time:</strong>
    <%= library.opening_time %>
  </p>

  <p>
    <strong>Closing time:</strong>
    <%= library.closing_time %>
  </p>

  <p>
    <strong>User:</strong>
    <%= library.user_id %>
  </p>

</div>

app/views/libraries/edit.html.erb
<h1>Editing library</h1>

<%= render "form", library: @library %>

<br>

<div>
  <%= link_to "Show this library", @library %> |
  <%= link_to "Back to libraries", libraries_path %>
</div>

app/views/libraries/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>libraries</h1>
<div id="libraries">
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Library name</th>
      <th scope="col">User name</th>
      <th scope="col">Created Date</th>
      <th scope="col">Updated Date</th>
      <th scope="col">View</th>
    </tr>
  </thead>
  <tbody>
<% i=1 %>
  <% @libraries.each do |library| %>  
<% # if book.user_id == current_user.id %>
      <tr>
      <th scope="row"> <%= i %> </th>
       <td> <%=  library.library_name %></td>
      <td><%= library.user_id %> </td>
      <td> <%= library.created_at %> </td>
      <td> <%= library.updated_at %> </td>
      <td>   <%= link_to "Show this library", library , class: "btn btn-success btn-sm " %> </td>
    </tr>
    <% i=i+1 %>
  <% #end %>
  <% end %>
</div>
<% if user_signed_in? %>
<%= link_to "Add New library", new_library_path , class: "btn btn-success btn-sm mb-5" %>
<% end %>

</tbody>
</table>

app/views/libraries/new.html.erb
<h1>New library</h1>

<%= render "form", library: @library %>

<br>

<div>
  <%= link_to "Back to libraries", libraries_path %>
</div>

app/views/libraries/show.html.erb
<%

if @book.empty?
      book_value = 'No books found' 
       count_book = 0
   else 
   count_book = @book.count 
  book_value =  @book.join(' , ')
 #  book_value = @book
   end

%>

<p style="color: green"><%= notice %></p>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"> <%= @library.library_name %> </h5>
    <h6 class="card-subtitle mb-2 text-muted mb-5"> <%= @library.user_id %> </h6>
    <h6 class="card-subtitle mb-2 text-muted mb-5"> Number of books in the library : <%= count_book %></h6>
    <h6 class="card-subtitle mb-2 text-muted mb-5"> <span class="text-primary">Books in the library</span> : <%=  book_value %> </h6>
    <h6 class="card-subtitle mb-2 text-muted"> Created date : <%= @library.created_at %> </h6>
    <h6 class="card-subtitle mb-2 text-muted">updated date : <%= @library.updated_at %> </h6> <br>
    <hr>
   
<%= link_to "Edit this library", edit_library_path(@library) , class: "card-link" %>

   <%= link_to "Back to books", books_path , class: "card-link"%>

    <%= button_to "Destroy this library", @library, method: :delete , class: "btn btn-danger btn-sm mt-5 "%>

  
  </div>
</div>

app/views/nabar/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light  navbar-dark bg-dark">
  <%= link_to "LibraryApp", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

 <li class="nav-item">
        <%= link_to "Libraries", libraries_path , class:"nav-link" %>
     </li>

       <li class="nav-item">
        <%= link_to "Books", books_path , class:"nav-link" %>
     </li>

       <% if user_signed_in? %>

    <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
     </li>

     <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
    </li>

      <% else %>

      <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>

<% end%>
    </ul>
  </div>
</nav>